
[Bindable] private var policyOneText:String = "This is Policy One. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var policyTwoText:String = "This is Policy Two. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var policyThreeText:String = "This is Policy Three. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var policyFourText:String = "This is Policy Four. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var policyFiveText:String = "This is Policy Five. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";
