[Bindable] private var flightText:String = "Flights are .....This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var accommodationText:String = "Accommodation is ....... This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var busText:String = "Scenic Bus tours...... This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var ferryText:String = "Scenic Ferry tours ..... This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var railText:String = "Scenic Rail is a ..... This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var vehicleHireText:String = "Vehicle hire is a good money spinner..... This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var cruiseText:String = "Cruises are available ..... is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var sightseeingText:String = "Sightseeing is .....ake my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";

[Bindable] private var travelInsuranceText:String = "Travel Insurance is ..... .....ake my page look better. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better. This is a short line of text. This is a short line of text. This is a much longer line of text that has nothing to do with anything, but will make my page look better.	";
